config/routes.rb
Rails.application.routes.draw do
  root "static#welcome"
  resources :tasks
  resources :buckets
	resources :users, only: [:create, :destroy] do
		collection do
			get :sign_up   
			get :sign_in
			get :profile
		end
	end
	post "/users/sign_in", to: "sessions#create", as: "login"
	delete "/users", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
    belongs_to :user
    has_many :tasks

    def self.get_by_status(status)
        self.all.select do |bucket|
            bucket.status == status
        end
    end

    def update_status
        if self.tasks == []
            self.status = "Empty"
        elsif self.tasks.any?{|task| task.status == "Pending"}
            self.status = "Pending"
        else
            self.status = "Completed"
        end
        self.save
    end

    def tasks_by_status(status)
        self.tasks.select do |task|
            task.status == status
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :bucket

  def self.get_by_status(status)
    self.all.select do |task|
        task.status == status
    end
  end
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord

  has_many :tasks, dependent: :destroy
  has_many :buckets, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true

  before_create :encrypt_password

  private
  def encrypt_password
    salted_pw = "c1#{self.password}css#{self.password}82$$c"
    self.password = Digest::SHA1.hexdigest(salted_pw)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

	helper_method :user_signed_in?, :current_user

	private

  def user_signed_in?
    session[:user_token] != nil
  end

  def current_user
    if user_signed_in?
      User.find(session[:user_token])
    else
      nil
    end
  end

	def check_login!
		if not user_signed_in?
			redirect_to "/users/sign_in"
		end
	end

	def record_not_found
		render file: "public/404.html", status: :not_found
	end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
	before_action :check_login!
    before_action :find_user_bucket, only: [:create, :show, :destroy]

    def index
        @empty_buckets = current_user.buckets.get_by_status("Empty")
        @pending_buckets = current_user.buckets.get_by_status("Pending")
        @completed_buckets = current_user.buckets.get_by_status("Completed")
    end

    def new
        @bucket = Bucket.new
    end

    def create
        @bucket = Bucket.create(post_params(:name, :description))
        @bucket.status = "Empty"
        @bucket.save
        redirect_to bucket_path(@bucket)
    end

    def show
        @bucket = Bucket.find(params[:id])
    end

    def edit
        @bucket = Bucket.find(params[:id])
    end

    def update
        @bucket = Bucket.find(params[:id])
        @bucket.update_status
        redirect_to bucket_path(@bucket)
    end

    def destroy
        @bucket = Bucket.find(params[:id]).destroy
        redirect_to buckets_path
    end

    private
    def post_params(*args)
        params.require(:bucket).permit(*args).merge(user_id: current_user.id)
    end

    def find_user_bucket
		@bucket = current_user.buckets.includes(:user)
	end
end

app/controllers/sessions_controller.rb
require 'digest'

class SessionsController < ApplicationController
  def create
    pw = user_params[:password]
    salted_pw = "c1#{pw}css#{pw}82$$c"
    hashed_password = Digest::SHA1.hexdigest(salted_pw)

    user = User.find_by(email: user_params[:email],
                        password: hashed_password)

    if user
      session[:user_token] = user.id
      redirect_to "/"
    else
      redirect_to "/users/sign_in"
    end
  end

  def destroy
    session[:user_token] = nil
    redirect_to "/"
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def welcome
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :check_login!
    before_action :find_user_task, only: [:create, :destroy]

    def index
        @pending_tasks = current_user.tasks.get_by_status("Pending")
        @completed_tasks = current_user.tasks.get_by_status("Completed")
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.create(post_params(:name, :description, :bucket_id))
        @task.status = "Pending"
        @task.save
            if current_user.tasks == []
                redirect_to "/"
            else
                @task.bucket.update_status
                redirect_to task_path(@task)
            end
    end

    def show
        @task = Task.find(params[:id])
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(post_params(:name, :description, :status, :bucket_id))
        @bucket = @task.bucket.update_status
        redirect_to task_path(@task)
    end

    def destroy
        @task = Task.find(params[:id]).destroy
        redirect_to tasks_path
    end

    private
    def post_params(*args)
        params.require(:task).permit(*args).merge(user_id: current_user.id)
    end

    def find_user_task
		@task = current_user.tasks.includes(:user)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
		@user = User.new
	end

	def sign_in
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to "/"
		else
			render :sign_up
		end
	end

  def destroy
		@user = User.find(current_user.id).destroy
		session[:user_token] = nil
		redirect_to "/"
  end

  def profile
	end

	private
	def user_params
		params.require(:user).permit(:email,
			                           :password,
																 :password_confirmation
																)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buckets/edit.html.erb
<h1><%= "EDIT: " + @bucket.name %></h1>
<%= form_for(@bucket) do |f| %>
    <br><%= f.label :description%><br>
    <p><%= @bucket.description %></p>
    <br><%= f.submit %><br>
<% end %>
<br><%= button_to "Delete Bucket", @bucket, :method => :delete, data: {confirm: 'Are you sure?'} %>

app/views/buckets/index.html.erb
<h1>BUCKETS LIST</h1>
<%= button_to "Create Bucket", new_bucket_path, method: :get %>
<h3>Empty Buckets</h3>
<ul class="list-unstyled">
<% @empty_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>
<h3>Pending Buckets</h3>
<ul class="list-unstyled">
<% @pending_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>
<h3>Completed Buckets</h3>
<ul class="list-unstyled">
<% @completed_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>

app/views/buckets/new.html.erb
<h1>CREATE NEW BUCKET</h1>
<%= form_for(@bucket) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.submit %>
<% end %>

app/views/buckets/show.html.erb
<h1><%= @bucket.name %></h1>
<p><%= @bucket.description %></p>
<h3>Pending Tasks</h3>
<ul class="list-unstyled">
    <% @bucket.tasks_by_status("Pending").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>
<h3>Completed Tasks</h3>
<ul class="list-unstyled">
    <% @bucket.tasks_by_status("Completed").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>
<%= button_to "Edit Bucket", edit_bucket_path(@bucket), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body  class="text-center" style="margin: 4em">
    <%= render "shared/navbar"%>
  <div class="container">
    <div class="row">
    <button type="button">
    <%= link_to "All Buckets", buckets_path%> | 
    <%= link_to "All Tasks", tasks_path%>
    <% if user_signed_in? %>  |
    <%= link_to "Profile", profile_users_path%>
    <% end %>
    </button>  
    <%= yield %>
    </div>
    <div style="margin: 4em">
    <%= button_to "Home", root_path, method: :get %>
    </div>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <div class="container login_form">
  <% if user_signed_in? %>
    <div class="login_label">
    <%= link_to "登出", logout_path, method: "delete" %> 
    <%= current_user.email %>
    </div>
  <% else %>
    <div class="login_label">
    <%= link_to "登入", sign_in_users_path %>
    <%= link_to "註冊", sign_up_users_path %>
    </div>
  <% end %>
  </div>
</nav>

app/views/tasks/edit.html.erb
<h1><%= "EDIT: " + @task.name %></h1>
<%= form_for(@task) do |f| %>
    <br><%= f.label :description%><br>
    <p><%= @task.description %></p>
    <br><%= f.label "Bucket"%>
    <%= f.collection_select :bucket_id, Bucket.where(user_id: current_user.id).order(:name),:id, :name %><br>
    <br><%= f.check_box :status, {}, "Completed", "Pending" %> Completed?<br>
    <br><%= f.submit %><br>
<% end %>
<br><%= button_to "Delete Task", @task, :method => :delete, data: {confirm: 'Are you sure?'} %>

app/views/tasks/index.html.erb
<h1>TASKS LIST</h1>
<%= button_to "Create Task", new_task_path, method: :get %>
<h3>Pending Tasks</h3>
<ul class="list-unstyled">
<% @pending_tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task) %></li>
<% end %>
</ul>
<h3>Completed Tasks</h3>
<ul class="list-unstyled">
<% @completed_tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task) %></li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<h1>CREATE NEW TASK</h1>
<%= form_for(@task) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.label "Bucket"%>
    <%= f.collection_select :bucket_id, Bucket.where(user_id: current_user.id).order(:name),:id, :name %><br>
    <br><%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p><%= @task.description %></p>
<h6><%= @task.status %></h6>
<%= button_to "Edit task", edit_task_path(@task), method: :get %>

app/views/users/profile.html.erb
<h1>會員資料</h1>
<%= current_user.email %>
<%= link_to "刪除", user_path(current_user.id), :method => :delete, data: {confirm: 'Are you sure?'} %> 

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_for(@user, url: login_path) do |f| %>
  <div class="field">
    <%= f.label "您的E-mail" %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label "請輸入密碼" %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit "登入" %></div>
<% end %>

app/views/users/sign_up.html.erb
<h1>註冊會員</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@user, url: "/users") do |f| %>

<div class="field">
  <%= f.label "您的E-mail" %>
  <%= f.email_field :email %>
</div>

<div class="field">
  <%= f.label "請輸入密碼" %>
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label "再確認密碼" %>
  <%= f.password_field :password_confirmation %>
</div>

<%= f.submit "創建帳號"%>
<% end %>